# Generated by Django 4.0.8 on 2024-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['carname']},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='car',
            name='carname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
