# Generated by Django 4.0.8 on 2024-07-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbase', '0002_alter_car_options_rename_name_car_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.CharField(max_length=200),
        ),
    ]
